### ISSUE TITLE
Unpinned maximized panel disappears

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#12]
## Description  
An unpinned maximized panel disappears if deactivated (lost focus).

 * version: 1.4.1
 * browser: Chrome

## Steps to reproduce  
Check this project
[https://codesandbox.io/s/ignite-ui-unpinned-panel-maximize-issue-230ir](https://codesandbox.io/s/ignite-ui-unpinned-panel-maximize-issue-230ir)

1. Open the "Content pane 1"
2. Maximize it
3. Click on the "+"
4. The panel is disappeared

## Result  
The panel is disappeared

## Expected result  
The panel, if deactivated, must go in the sidebar, like when it's closed.

## Attachments  
[https://codesandbox.io/s/ignite-ui-unpinned-panel-maximize-issue-230ir](https://codesandbox.io/s/ignite-ui-unpinned-panel-maximize-issue-230ir)

**Comment by gedinakova** [comment]
@omanzelli This issue should be resolved in the latest release. Please, note, however, that the overlay containing the menu will not be visible because it is rendered behind the maximized pane. This is an issue with the z-indices - the dx-overlay-wrapper has a z-index in the 1000s while our content pane's z-index is in the 10000s. So, on application level, the z-indices need to be adjusted accordingly in order for the menu to appear correctly.
