### ISSUE TITLE
Dock manager panel resize error

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#15]
## Description  
The Dock Manager throws an error resizing the split panel.

 * igniteui-angular version: 1.6.0
 * browser: Chrome

## Steps to reproduce  

1. Create two panel inside a split panel
2. Resize the split panel

## Result  
The panels are resized but this error is shown
```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at I.F.dragMove (igc-button-component_20.entry.js:3137)
    at HTMLHtmlElement.I.handleMouseMove (igc-button-component_20.entry.js:2791)
    at c.invokeTask (zone-evergreen.js:406)
    at a.runTask (zone-evergreen.js:178)
    at u.invokeTask [as invoke] (zone-evergreen.js:487)
    at _ (zone-evergreen.js:1600)
    at HTMLHtmlElement.m (zone-evergreen.js:1626)
```

## Expected result  
No error

**Comment by gedinakova** [comment]
@omanzelli Can you, please, send us a small sample application, demonstrating the issue? We tested with [this sample](https://stackblitz.com/edit/github-jt4sfw?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.ts) but we can't reproduce it! Thanks in advance!

**Comment by omanzelli** [comment]
> @omanzelli Can you, please, send us a small sample application, demonstrating the issue? We tested with [this sample](https://stackblitz.com/edit/github-jt4sfw?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.ts) but we can't reproduce it! Thanks in advance!

I'll try!

**Comment by omanzelli** [comment]
@gedinakova here a [sample application](https://stackblitz.com/edit/github-jt4sfw-kbknte?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.html) how I'm managing the dock manager.

At the top there is a "menu" that changes the layout.
You can save the layout in the browser local storage and load it.

I'm not able to reproduce the error but there is a strange behavior: the content of the panels is not present.
Only in the Preview and Column selection panel there the text.

![image](https://user-images.githubusercontent.com/70320904/141499612-e99649c0-4ac4-4d4a-a50e-ab7912a477b7.png)

Could this strange behavior be associated to the error?

**Comment by gedinakova** [comment]
@omanzelli Sorry, for the delayed reply (I was on a sick leave for a while). I reviewed the sample application above and noticed that the missing content is caused by a typo in the ngIf directives' conditions used on the content divs. The issue is that the string constants are members of the dockManagerService, not of the component. So correcting the `*ngIf="this.selectedDrawer == this.CONTEXT_COLUMNS_ID"` to `*ngIf="this.selectedDrawer == this.dockManagerService.CONTEXT_COLUMNS_ID"` fixes the problem. I updated [the sample](https://stackblitz.com/edit/github-jt4sfw-kd683s?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.html) as well.
Please, let us know if you need further assistance.
