### ISSUE TITLE
Issue on pin/unpin when pane's headerId is defined

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-dockmanager#2]
## Description  
When headerId of some pinned pane is set to slot like for example the following:
```
 <div slot="header1" class="header-slot">
    <span >Pane 1</span>
    <div class="additional-buttons">
    <button #btn igxButton="icon" (click)="deleteButton(btn)">
        <igx-icon class="custom-button">delete</igx-icon>
    </button>
    </div>
</div>
```
and the user unpin the pane it's header is not visible in the area where all unpinned panes are displayed.
## Steps to reproduce  

1. Create IgcDockManager with several panes
2. Set the slot above to the headerId of some of the panes
3. Unpin this pane

## Result  
![image](https://user-images.githubusercontent.com/52423497/100985520-c3985f00-3554-11eb-9671-923a9e8e26d1.png)

## Expected result  
![image](https://user-images.githubusercontent.com/52423497/100985785-0bb78180-3555-11eb-91f4-17879a5ce0d7.png)

**Comment by DiyanDimitrov** [comment]
Since a `slot` can be projected at a single place in the DOM, we have decided to expose different slot properties for each location the header is displayed:
- `headerId` - slot rendered in the content pane header
- `tabHeaderId` - slot rendered in the tab header
- `unpinnedHeaderId` - slot rendered in the unpinned pane header

If any of these slot properties is not set, the value of the `header` property will be rendered.
