### ISSUE TITLE
Disable drag options

### ISSUE THREAD

**Issue by michalsgit** [IgniteUI/igniteui-dockmanager#4]
## Is your feature request related to a problem? Please describe.
Allow to disable dragging windows sizes and reposition of the windows in DockManager

## Describe the solution you'd like
Application users should not be able to resize or reposition windows but should be able to maximize them.

**Comment by gedinakova** [comment]
Hello @michalsgit,

Dragging the floating windows around can be forbidden via handling the DockManager's paneDragOver event and setting the isValid property to false. Currently, the resizing of these windows cannot be forbidden but we may consider adding an event which you can handle and cancel the resize operation. Please, let us know if this would work for you?

I created a [small sample](https://codesandbox.io/s/silent-waterfall-624e6?file=/src/DockManagerOverview.ts) demonstrating the approach with handling the paneDragOver to prevent the floating panes from moving around.

**Comment by michalsgit** [comment]
Canceling resize operation could help but it will be still confusing for users as clicking on the border shows arrow that implies the resize operation is possible.

**Comment by DiyanDimitrov** [comment]
@michalsgit. your point is valid that's why we have decided to add two new properties:
-  `allowFloatingPanesResize` property of the `IgcDockManagerComponent` enables/disables the resizing of all floating panes inside the dock manager
- `floatingResizable` of the `IgcSplitPane` enables/disabled the resize of a specific floating pane
