### ISSUE TITLE
Closing split panes causes all panes to close 

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-dockmanager#94]
Run sample
https://stackblitz.com/edit/hb5uzc

Steps: Close floating pane and tab 1

**Result**: All tabs are closed.

**Recommended solution**: Add allowClose to split panes and other types that do not support it and/or only close active pane one at a time.

**Comment by nshukin** [comment]
Hi team, any updates?

**Comment by gedinakova** [comment]
Hello, if I understand correctly you aim is to close the tabs one by one. This is possible by simply using the menu on the tab itself. The header button is indeed meant to close the whole tabgrouppane.

**Comment by nshukin** [comment]
This issue is opened because of https://account.infragistics.com/support-cases/500VM00000BHbjFYAT
Long story short, there is a problem with Pane layout, created dynamically.
E.g. ![Issue1](https://github.com/IgniteUI/igniteui-dockmanager/assets/170625187/d49e3745-9461-4039-b9e8-417c5a1d5855)
When splitPane contains two content panes and I need to remove close button from the parent - splitPane (in order to forbid a user to close all inner/child panes by closing the parent one). The request is allow to close the splitPane (since it could be the parent for content panes)

**Comment by nshukin** [comment]
Hi team. This bug fix / enhancement is very important for me. I see that there are no actions with it. What is the actual progress?

**Comment by igdmdimitrov** [comment]
Hi @nshukin. We will schedule this for development.

**Comment by mddifilippo89** [comment]
@igdmdimitrov 
What is the ETA for this? This is considered blocking for @nshukin

**Comment by gedinakova** [comment]
Hello @nshukin & @mddifilippo89,

We started looking into this issue. We identified two things we can implement in order to support such scenarios:
- First, we will add a `closeBehavior` property to the dockManager which will control what would happen when clicking the close button of a content pane when it's part of a tab group pane. The options would be `selectedPane` and `allPanes`.
- Second, we will add a searate part for the close button of floating windows, which will allow us to customize this button so it can be, for instance, disabled under certain conditions.
The ETA to release this implementation would be 3 weeks from now.

As this seems to be critical for your project, for the time being I can recommend handling the `paneClose` event and prevent closing all panes manually. I implemented this approach in [this sample](https://stackblitz.com/edit/hb5uzc-pgnmtt?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.ts).
Please, let us know if we can be of further assistance.

**Comment by nshukin** [comment]
Hey @gedinakova thank you, really appreciate it. I'll try the  paneClose event and waiting the update

**Comment by gedinakova** [comment]
Released in 1.15.0
